# write down 20 in built method on pandas

# A. PANDAS IN BUILT FUNCTIONS

In [2]:
import pandas as pd
import numpy as np

In [3]:
# 1.  To read a csv file use the methode read_csv ** Read Salaries.csv as a dataframe called sal.**


sal= pd.read_csv(r'C:\Users\Vineyard\Documents\Salaries.csv')

In [4]:
# 2.  Return the five `n` of rows.** Check the head of the DataFrame.
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [5]:
#3. Return the last `n` rows.
sal.tail()

Id   EmployeeName                    JobTitle  BasePay  \
148649  148650  Roy I Tillery                   Custodian      0.0   
148650  148651   Not provided                Not provided      NaN   
148651  148652   Not provided                Not provided      NaN   
148652  148653   Not provided                Not provided      NaN   
148653  148654      Joe Lopez  Counselor, Log Cabin Ranch      0.0   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
148649          0.0      0.00       0.0      0.00              0.00  2014   
148650          NaN       NaN       NaN      0.00              0.00  2014   
148651          NaN       NaN       NaN      0.00              0.00  2014   
148652          NaN       NaN       NaN      0.00              0.00  2014   
148653          0.0   -618.13       0.0   -618.13           -618.13  2014   

        Notes         Agency  Status  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN

In [6]:
# 4.  describe()***Generate descriptive statistics.
sal.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

In [7]:
# 5. Print a concise summary of a DataFrame
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [8]:
# Memory usage of DataFrame columns.
sal.memory_usage()

Index                   128
Id                  1189232
EmployeeName        1189232
JobTitle            1189232
BasePay             1189232
OvertimePay         1189232
OtherPay            1189232
Benefits            1189232
TotalPay            1189232
TotalPayBenefits    1189232
Year                1189232
Notes               1189232
Agency              1189232
Status              1189232
dtype: int64

In [9]:
# 6. Return a tuple representing the dimensionality of the DataFrame.

sal.shape

(148654, 13)

In [10]:
# 7. to check the type of data
type(sal)

pandas.core.frame.DataFrame

In [11]:
# 8. Renaming columns
sal.rename(columns = {'OvertimePay': 'Additional work pay'})

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        Additional work pay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0                      0.00  400184.25       NaN  567595.43         567595.43   
1                 245131.88  137811.38       NaN  538909.28         538909.28   
2                 106088.18   16452.60       NaN  335279.91         335279.91   
3                  56120.71  198306.90       NaN  332343.61         332343.61   
4                   9737.00  182234.59       NaN  326373.19         326373.19   
...                     ...        ...       ...        ...               ...   
148649                 0.00       0.00       0.0       0.00              0.00   
148650                  NaN        NaN       NaN       0.00              0.00   
148651                  NaN        NaN       NaN       0.00              0.00   
148652                  NaN        NaN       NaN       0.00              0.00   
148653                 0.00    -618.13       0.0    -618.13           -618.13   

        Year  Notes         Agency  Status  
0       2011    NaN  San Francisco     NaN  
1       2011    NaN  San Francisco     NaN  
2       2011    NaN  San Francisco     NaN  
3       2011    NaN  San Francisco     NaN  
4       2011    NaN  San Francisco     NaN  
...      ...    ...            ...     ...  
148649  2014    NaN  San Francisco     NaN  
148650  2014    NaN  San Francisco     NaN  
148651  2014    NaN  San Francisco     NaN  
148652  2014    NaN  San Francisco     NaN  
148653  2014    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [12]:
# 9. deleting columns
#print(sal.drop(columns = ['Notes']))
newdf= sal.drop(columns = ['Notes'])
newdf

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

               Agency  Status  
0       San Francisco     NaN  
1       San Francisco     NaN  
2       San Francisco     NaN  
3       San Francisco     NaN  
4       San Francisco     NaN  
...               ...     ...  
148649  San Francisco     NaN  
148650  San Francisco     NaN  
148651  San Francisco     NaN  
148652  San Francisco     NaN  
148653  San Francisco     NaN  

[148654 rows x 12 columns]

In [13]:
#deleting coloum and replacing the new dataframe
newdf.drop('Status',axis=1,inplace=True)

In [14]:
# 10. A groupby operation involves some combination of splitting the
#object, applying a function, and combining the results. This can be
#used to group large amounts of data and compute operations on these
#groups.


newdf.groupby('Year').mean()['BasePay']

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [15]:
newdf.groupby('Year')['BasePay'].sum()

Year
2011    2.299566e+09
2012    2.405835e+09
2013    2.576381e+09
2014    2.537369e+09
Name: BasePay, dtype: float64

In [35]:
newdf.groupby('Year').agg({'BasePay':sum})

BasePay
Year              
2011  2.299566e+09
2012  2.405835e+09
2013  2.576381e+09
2014  2.537369e+09

In [37]:
newdf.groupby('Year').agg({'BasePay':sum}).round(2)

BasePay
Year              
2011  2.299566e+09
2012  2.405835e+09
2013  2.576381e+09
2014  2.537369e+09

In [ ]:
np.round_(,2) 

In [16]:
newdf.groupby('Year').sum()['BasePay']

Year
2011    2.299566e+09
2012    2.405835e+09
2013    2.576381e+09
2014    2.537369e+09
Name: BasePay, dtype: float64

In [17]:
newdf.groupby('Year').max()['BasePay']

Year
2011    294580.02
2012    302578.00
2013    319275.01
2014    318835.49
Name: BasePay, dtype: float64

In [18]:
# 11. nunique() Count number of distinct elements in specified axis.
newdf['JobTitle'].nunique()

2159

In [19]:
newdf['Agency'].nunique()

1

In [20]:
# 12. Return the maximum of the values over the requested axis.
newdf['BasePay'].max()

319275.01

In [21]:
# 13. Return the minimum of the values over the requested axis.
newdf['BasePay'].min()

-166.01

In [22]:
# 14. Return the avearge of the values over the requested axis.
newdf['BasePay'].mean()

66325.44884050643

In [23]:
# 15.  to select position **Purely integer-location based indexing for selection by position**.
newdf.iloc[0:3]

Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2    GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3  ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   

   Year         Agency  
0  2011  San Francisco  
1  2011  San Francisco  
2  2011  San Francisco

In [24]:
# 16 # Reset to default 0,1...n index
newdf.reset_index()

index      Id       EmployeeName  \
0            0       1     NATHANIEL FORD   
1            1       2       GARY JIMENEZ   
2            2       3     ALBERT PARDINI   
3            3       4  CHRISTOPHER CHONG   
4            4       5    PATRICK GARDNER   
...        ...     ...                ...   
148649  148649  148650      Roy I Tillery   
148650  148650  148651       Not provided   
148651  148651  148652       Not provided   
148652  148652  148653       Not provided   
148653  148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

               Agency  
0       San Francisco  
1       San Francisco  
2       San Francisco  
3       San Francisco  
4       San Francisco  
...               ...  
148649  San Francisco  
148650  San Francisco  
148651  San Francisco  
148652  San Francisco  
148653  San Francisco  

[148654 rows x 12 columns]

In [25]:
# 17. Fill NA/NaN values using the specified method.
newdf.fillna(value='FILL VALUE')

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle     BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)   155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)   212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC     77916.0   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)    134401.6   
...                                                ...         ...   
148649                                       Custodian         0.0   
148650                                    Not provided  FILL VALUE   
148651                                    Not provided  FILL VALUE   
148652                                    Not provided  FILL VALUE   
148653                      Counselor, Log Cabin Ranch         0.0   

       OvertimePay    OtherPay    Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.0   400184.25  FILL VALUE  567595.43         567595.43  2011   
1        245131.88   137811.38  FILL VALUE  538909.28         538909.28  2011   
2        106088.18     16452.6  FILL VALUE  335279.91         335279.91  2011   
3         56120.71    198306.9  FILL VALUE  332343.61         332343.61  2011   
4           9737.0   182234.59  FILL VALUE  326373.19         326373.19  2011   
...            ...         ...         ...        ...               ...   ...   
148649         0.0         0.0         0.0       0.00              0.00  2014   
148650  FILL VALUE  FILL VALUE  FILL VALUE       0.00              0.00  2014   
148651  FILL VALUE  FILL VALUE  FILL VALUE       0.00              0.00  2014   
148652  FILL VALUE  FILL VALUE  FILL VALUE       0.00              0.00  2014   
148653         0.0     -618.13         0.0    -618.13           -618.13  2014   

               Agency  
0       San Francisco  
1       San Francisco  
2       San Francisco  
3       San Francisco  
4       San Francisco  
...               ...  
148649  San Francisco  
148650  San Francisco  
148651  San Francisco  
148652  San Francisco  
148653  San Francisco  

[148654 rows x 11 columns]

In [26]:
# Fill NA/NaN values using the mean of the overtimepay method.
newdf['OvertimePay'].fillna(value=newdf['OvertimePay'].mean())

0              0.000000
1         245131.880000
2         106088.180000
3          56120.710000
4           9737.000000
              ...      
148649         0.000000
148650      5066.059886
148651      5066.059886
148652      5066.059886
148653         0.000000
Name: OvertimePay, Length: 148654, dtype: float64

In [27]:
#Fill NA/NaN values with 0.
newdf.fillna(0)

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       0.0  567595.43         567595.43  2011   
1         245131.88  137811.38       0.0  538909.28         538909.28  2011   
2         106088.18   16452.60       0.0  335279.91         335279.91  2011   
3          56120.71  198306.90       0.0  332343.61         332343.61  2011   
4           9737.00  182234.59       0.0  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650         0.00       0.00       0.0       0.00              0.00  2014   
148651         0.00       0.00       0.0       0.00              0.00  2014   
148652         0.00       0.00       0.0       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

               Agency  
0       San Francisco  
1       San Francisco  
2       San Francisco  
3       San Francisco  
4       San Francisco  
...               ...  
148649  San Francisco  
148650  San Francisco  
148651  San Francisco  
148652  San Francisco  
148653  San Francisco  

[148654 rows x 11 columns]

In [28]:
# 18a) Drop the columns where at least one element is missing.
newdf.dropna(axis='columns')

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  Year         Agency  
0              567595.43  2011  San Francisco  
1              538909.28  2011  San Francisco  
2              335279.91  2011  San Francisco  
3              332343.61  2011  San Francisco  
4              326373.19  2011  San Francisco  
...                  ...   ...            ...  
148649              0.00  2014  San Francisco  
148650              0.00  2014  San Francisco  
148651              0.00  2014  San Francisco  
148652              0.00  2014  San Francisco  
148653           -618.13  2014  San Francisco  

[148654 rows x 7 columns]

In [29]:
# 18b. Drop the rows where at least one element is missing.***Remove missing values.
newdf.dropna()

Id        EmployeeName                      JobTitle    BasePay  \
36159    36160      Gary Altenberg  Lieutenant, Fire Suppression  128808.87   
36160    36161        Gregory Suhr               Chief of Police  302578.00   
36161    36162          Khoa Trinh   Electronic Maintenance Tech  111921.00   
36162    36163  Joanne Hayes-White        Chief, Fire Department  296943.01   
36163    36164   Frederick Binkley     EMT/Paramedic/Firefighter  126863.19   
...        ...                 ...                           ...        ...   
148645  148646    Carolyn A Wilson     Human Services Technician       0.00   
148647  148648      Joann Anderson   Communications Dispatcher 2       0.00   
148648  148649         Leon Walker                     Custodian       0.00   
148649  148650       Roy I Tillery                     Custodian       0.00   
148653  148654           Joe Lopez    Counselor, Log Cabin Ranch       0.00   

        OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
36159     220909.48  13126.31  44430.12  362844.66         407274.78  2012   
36160          0.00  18974.11  69810.19  321552.11         391362.30  2012   
36161     146415.32  78057.41  53102.29  336393.73         389496.02  2012   
36162          0.00  17816.59  72047.88  314759.60         386807.48  2012   
36163     192424.49  17917.18  44438.25  337204.86         381643.11  2012   
...             ...       ...       ...        ...               ...   ...   
148645         0.00      0.00      0.00       0.00              0.00  2014   
148647         0.00      0.00      0.00       0.00              0.00  2014   
148648         0.00      0.00      0.00       0.00              0.00  2014   
148649         0.00      0.00      0.00       0.00              0.00  2014   
148653         0.00   -618.13      0.00    -618.13           -618.13  2014   

               Agency  
36159   San Francisco  
36160   San Francisco  
36161   San Francisco  
36162   San Francisco  
36163   San Francisco  
...               ...  
148645  San Francisco  
148647  San Francisco  
148648  San Francisco  
148649  San Francisco  
148653  San Francisco  

[111886 rows x 11 columns]

In [30]:
# 19. To get column name
newdf.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Agency'],
      dtype='object')

In [31]:
newdf[newdf['EmployeeName']=='Carolyn A Wilson'].count()

Id                  2
EmployeeName        2
JobTitle            2
BasePay             2
OvertimePay         2
OtherPay            2
Benefits            2
TotalPay            2
TotalPayBenefits    2
Year                2
Agency              2
dtype: int64

In [32]:
# 20.Count non-NA cells for each column or row. # it doesnt count NAN 

newdf[newdf['JobTitle']=='Custodian'].count()

Id                  2418
EmployeeName        2418
JobTitle            2418
BasePay             2409
OvertimePay         2418
OtherPay            2418
Benefits            2418
TotalPay            2418
TotalPayBenefits    2418
Year                2418
Agency              2418
dtype: int64

# B. NUMPY IN BUILT FUNCTIONS

In [107]:
# 1. arange() Return evenly spaced values within a given interval.
arr= np.arange(0,12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [108]:
# 2.  to check the data type
arr.dtype

dtype('int32')

In [109]:
# 3. Returns an array containing the same data with a new shape
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
arr.reshape(3,4).shape

(3, 4)

In [111]:
# 4. Return the maximum along a given axis.
#np.max(arr) ** this can also be used for maximum
arr.max()

11

In [112]:
# 5. Return the minimum along a given axis.
arr.min()

0

In [113]:
# 5. Returns the average of the array elements along given axis
arr.mean()

5.5

In [114]:
# 6. Taking Square Roots **Return the non-negative square-root of an array, element-wise.
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [115]:
# 7. Calcualting exponential (e^) **Calculate the exponential of all elements in the input array.
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [116]:
# 8. Trigonometric sine, element-wise.
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021])

In [117]:
# 9. Natural logarithm, element-wise.**The natural logarithm `log` is the inverse of the exponential function,
np.log(arr)

C:\Users\Vineyard\AppData\Local\Temp\ipykernel_6532\3355893438.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527])

In [118]:
# 10. Return the sum of the array elements over the given axis.
arr.sum()

66

In [119]:
# 11. Returns the standard deviation of the array elements along given axis.
arr.std()

3.452052529534663

In [130]:
a= ([2.422,5.834,1.234,3.834])
np.array(a)
a

[2.422, 5.834, 1.234, 3.834]

In [131]:
#12. Return the floor of the input, element-wise.
floor_a = np.floor(a)
print(floor_a)

[2. 5. 1. 3.]


In [133]:
# 13. Round an array to the given number of decimals.
rounded_a = np.round_(a,2) # rounding to two decimals
print(rounded_a)

[2.42 5.83 1.23 3.83]


In [136]:
# 14. Return evenly spaced numbers over a specified interval.

np.linspace(4,10,11)

array([ 4. ,  4.6,  5.2,  5.8,  6.4,  7. ,  7.6,  8.2,  8.8,  9.4, 10. ])

In [137]:
#15. Repeat elements of an array.
np.repeat(2,10)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [145]:
# roll a dice
np.random.choice([1,2,3,4,5,6])


2

In [144]:
# 16. Generates a random sample from a given 1-D array
#This is equivalent to np.random.randint(0,5,3)
np.arange(5,3)
np.random.choice([5,3])

3

In [146]:
# 17 Fill the array with a scalar value.
arr.fill(12)
arr

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [148]:
# 18 Uniformly distributed floats over
np.random.rand(1)

array([0.94653531])

In [150]:
# 19 Uniformly distributed integer over
np.random.randint(1,10)

7

In [153]:
# 20. An array object satisfying the specified requirements.


np.array((1,2,3,4,5,6,7,8))

array([1, 2, 3, 4, 5, 6, 7, 8])

# THE END